/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    activities: Activity;
    'package-categories': PackageCategory;
    'option-groups': OptionGroup;
    options: Option;
    packages: Package;
    'group-extras': GroupExtra;
    orders: Order;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    activities: ActivitiesSelect<false> | ActivitiesSelect<true>;
    'package-categories': PackageCategoriesSelect<false> | PackageCategoriesSelect<true>;
    'option-groups': OptionGroupsSelect<false> | OptionGroupsSelect<true>;
    options: OptionsSelect<false> | OptionsSelect<true>;
    packages: PackagesSelect<false> | PackagesSelect<true>;
    'group-extras': GroupExtrasSelect<false> | GroupExtrasSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Image description for accessibility and SEO.
   */
  alt: string;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities".
 */
export interface Activity {
  id: string;
  title: string;
  /**
   * Short summary shown on activity cards.
   */
  description?: string | null;
  /**
   * Auto-generated from title.
   */
  slug: string;
  image?: (string | null) | Media;
  sort?: number | null;
  /**
   * Optional group add-ons shown in the «Improve your activity» tab.
   */
  groupExtras?: (string | GroupExtra)[] | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "group-extras".
 */
export interface GroupExtra {
  id: string;
  name: string;
  /**
   * Auto-generated from name.
   */
  slug: string;
  /**
   * Group extra price in cents (EUR).
   */
  priceCents: number;
  image?: (string | null) | Media;
  sort?: number | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "package-categories".
 */
export interface PackageCategory {
  id: string;
  activity: string | Activity;
  title: string;
  /**
   * Short summary shown on category cards.
   */
  description?: string | null;
  /**
   * Age requirement label (e.g. "+12 Anos").
   */
  minAge?: string | null;
  /**
   * Auto-generated from activity and title.
   */
  slug: string;
  image?: (string | null) | Media;
  sort?: number | null;
  /**
   * Optional group add-ons shown in the «Improve your activity» tab.
   */
  groupExtras?: (string | GroupExtra)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "option-groups".
 */
export interface OptionGroup {
  id: string;
  title: string;
  selectionType: 'single' | 'multi';
  sort?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "options".
 */
export interface Option {
  id: string;
  group: string | OptionGroup;
  label: string;
  /**
   * Optional fallback price. Package-specific pricing in Packages usually overrides this.
   */
  defaultPriceCents?: number | null;
  pricingUnit: 'per_person' | 'per_booking';
  cartBehavior: 'inline' | 'separate_line_item';
  /**
   * Maximum quantity per booking (e.g. 1 for Private Lounge).
   */
  maxPerBooking?: number | null;
  sort?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages".
 */
export interface Package {
  id: string;
  activity: string | Activity;
  /**
   * Optional middle layer (e.g. Paintball Group, Birthday Party). Leave empty when not used.
   */
  category?: (string | null) | PackageCategory;
  name: string;
  /**
   * Auto-generated from activity, category, and name.
   */
  slug: string;
  image?: (string | null) | Media;
  /**
   * Base package price in cents (EUR).
   */
  basePriceCents: number;
  isActive?: boolean | null;
  sort?: number | null;
  /**
   * Shows "(MOST POPULAR)" prominently as the first list item on the card.
   */
  isMostPopular?: boolean | null;
  /**
   * Included items shown on the pricing card (e.g. paintballs, gear, insurance).
   */
  highlights?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Inherit extra configuration from another package (e.g. Commando Party → Commando). Apply overrides below.
   */
  templatePackage?: (string | null) | Package;
  /**
   * Mutations applied on top of the template package configuration.
   */
  templateOverrides?:
    | {
        type: 'replaceOption' | 'excludeOption' | 'addOption' | 'setDefault' | 'priceOverride';
        group: string | OptionGroup;
        fromOption?: (string | null) | Option;
        toOption?: (string | null) | Option;
        isDefault?: boolean | null;
        /**
         * Package-specific price in cents for the added or replaced option.
         */
        priceCents?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Full extra configuration for this package. Not used when a template package is set.
   */
  extraGroupConfigs?:
    | {
        group: string | OptionGroup;
        sort?: number | null;
        options: {
          option: string | Option;
          /**
           * Pre-selected choice for this package in this group.
           */
          isDefault?: boolean | null;
          /**
           * Add-on price for this package (0 = included with the default selection).
           */
          priceCents: number;
          id?: string | null;
        }[];
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  /**
   * Order identifier (max 25 chars for Multibanco).
   */
  orderNumber: string;
  /**
   * Multibanco: mark as Paid manually on visit day. PayPal: updated automatically.
   */
  status: 'pending' | 'awaiting_payment' | 'paid' | 'failed' | 'expired' | 'cancelled';
  paymentMethod: 'multibanco' | 'paypal';
  customerFirstName: string;
  customerLastName: string;
  customerEmail: string;
  customerPhone?: string | null;
  customerAddress: string;
  customerPostalCode: string;
  customerCity: string;
  customerCountry: string;
  customerNif?: string | null;
  acceptMarketing?: boolean | null;
  observations?: string | null;
  items:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Order total in EUR.
   */
  totalAmount: number;
  multibancoEntity?: string | null;
  /**
   * Multibanco reference shown to the customer.
   */
  multibancoReference?: string | null;
  multibancoRequestId?: string | null;
  paypalOrderId?: string | null;
  /**
   * Raw payment provider response metadata.
   */
  paymentDetails?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'activities';
        value: string | Activity;
      } | null)
    | ({
        relationTo: 'package-categories';
        value: string | PackageCategory;
      } | null)
    | ({
        relationTo: 'option-groups';
        value: string | OptionGroup;
      } | null)
    | ({
        relationTo: 'options';
        value: string | Option;
      } | null)
    | ({
        relationTo: 'packages';
        value: string | Package;
      } | null)
    | ({
        relationTo: 'group-extras';
        value: string | GroupExtra;
      } | null)
    | ({
        relationTo: 'orders';
        value: string | Order;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "activities_select".
 */
export interface ActivitiesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  slug?: T;
  image?: T;
  sort?: T;
  groupExtras?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "package-categories_select".
 */
export interface PackageCategoriesSelect<T extends boolean = true> {
  activity?: T;
  title?: T;
  description?: T;
  minAge?: T;
  slug?: T;
  image?: T;
  sort?: T;
  groupExtras?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "group-extras_select".
 */
export interface GroupExtrasSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  priceCents?: T;
  image?: T;
  sort?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "option-groups_select".
 */
export interface OptionGroupsSelect<T extends boolean = true> {
  title?: T;
  selectionType?: T;
  sort?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "options_select".
 */
export interface OptionsSelect<T extends boolean = true> {
  group?: T;
  label?: T;
  defaultPriceCents?: T;
  pricingUnit?: T;
  cartBehavior?: T;
  maxPerBooking?: T;
  sort?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "packages_select".
 */
export interface PackagesSelect<T extends boolean = true> {
  activity?: T;
  category?: T;
  name?: T;
  slug?: T;
  image?: T;
  basePriceCents?: T;
  isActive?: T;
  sort?: T;
  isMostPopular?: T;
  highlights?:
    | T
    | {
        label?: T;
        id?: T;
      };
  templatePackage?: T;
  templateOverrides?:
    | T
    | {
        type?: T;
        group?: T;
        fromOption?: T;
        toOption?: T;
        isDefault?: T;
        priceCents?: T;
        id?: T;
      };
  extraGroupConfigs?:
    | T
    | {
        group?: T;
        sort?: T;
        options?:
          | T
          | {
              option?: T;
              isDefault?: T;
              priceCents?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  orderNumber?: T;
  status?: T;
  paymentMethod?: T;
  customerFirstName?: T;
  customerLastName?: T;
  customerEmail?: T;
  customerPhone?: T;
  customerAddress?: T;
  customerPostalCode?: T;
  customerCity?: T;
  customerCountry?: T;
  customerNif?: T;
  acceptMarketing?: T;
  observations?: T;
  items?: T;
  totalAmount?: T;
  multibancoEntity?: T;
  multibancoReference?: T;
  multibancoRequestId?: T;
  paypalOrderId?: T;
  paymentDetails?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}